all: avl1 avl2 avl3 avl4

avl1: avl1.cpp
	g++ avl1.cpp -o avl1

avl2: avl2.cpp
	g++ avl2.cpp -o avl2

avl3: avl3.c
	gcc avl3.c -o avl3

avl4: avl4.cpp
	g++ avl4.cpp -o avl4

clean:
	rm -rf *.o avl1 avl2 avl3
