all: nqueens1 nqueens2 nqueens3

nqueens1: nqueens1.c
	gcc nqueens1.c -o nqueens1

nqueens2: nqueens2.c
	gcc nqueens2.c -o nqueens2

nqueens3: nqueens3.cpp
	g++ nqueens3.cpp -o nqueens3

clean:
	rm -rf *.o nqueens1 nqueens2 nqueens3

